import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from "next/link"

const Home: NextPage = () => {

  const fetcher = (...args: Parameters<typeof fetch>) => fetch(...args).then((res) => res.json())
  const { data, error, } = useSWR('/api/leaders', fetcher)
  const router = useRouter();
  let eventPeriod = "start"

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>
  // ``,
  return (
    <div className={styles.container}>
      <Head>
        <title>Leaders Connect By CMFest Africa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={`https://twitter.com/share?&hashtags=CMFest22&text=Hi Jamin @0xJamin, I just found you at the @cmfestafrica Festival I'd love to connect with you and learn from you, cheers &`}>
    <a target="_blank">Click this link</a>
</Link>
      {/* <main className={styles.main}>
        <div>
          <h1>Hello World, This is supposed to show something here</h1>
          <div>
            {
              data && <p>Hi {data?.name} is just scanned my tag and found you at #CMFest22 looking to connect to your profile { `https://twitter.com/${data?.username}` }</p>
            }
          </div>
        </div>
      </main> */}


    </div>
  )
}

export default Home
